
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: wordpress-persistent-storage
    labels:
      type: local
      name: wordpress-persistent-storage
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: local-storage
    hostPath:
      path: "/var/lib/html"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
  labels:
    name: mysql-persistent-storage
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
